micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:keymanager}?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    dialect: MYSQL_5_7
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024